In [4]:
#This will be a Neural Network without any hidden layers aka Perceptron.
import numpy as np

In [11]:
#define the sigmoid function
#define the sigmoid derivative to calculate the adjustment
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

In [12]:
#Defining the training example, here with the inputs

training_inputs =np.array([[0,0,1],
                           [1,1,1],
                           [1,0,1],
                           [0,1,1]])

In [13]:
#Here will be the training outputs, also transpose it to become a 4x1 matrix

training_outputs = np.array([[0,1,1,0]]).T

#initialize the weights by assigning a random value

np.random.seed(1)

#3x1 matrix because we have 3 inputs and 1 output value these will be random values from -1 to 1 with a mean of 0
synaptic_weights = 2 * np.random.random((3, 1)) -1

print('Random starting synaptic weights: ')
print(synaptic_weights)

#Here will be the for loop, keep in mid np.dot is element wise multiplication mtarices
for iteration in range(20000):
    
    input_layer = training_inputs
    
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))
    
    error = training_outputs - outputs
    
    adjustments = error * sigmoid_derivative(outputs)
    
    synaptic_weights += np.dot(input_layer.T, adjustments)
    
#print the synpatic weights after training
print('Synapticweights after training')
print(synaptic_weights)
    
print('Outputs after training: ')
print(outputs)

Random starting synaptic weights: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Synapticweights after training
[[10.38040701]
 [-0.20641179]
 [-4.98452047]]
Outputs after training: 
[[0.00679672]
 [0.99445583]
 [0.99548516]
 [0.00553614]]
